[package]
name = "hydro"
version = "0.1.0"
authors = ["Thomas Gillen <thomas.gillen@googlemail.com>"]
edition = "2018"

[dependencies]
slog = "2"
slog-stdlog = "3"
parking_lot = "0.7"
downcast-rs = "1.0"
itertools = "0.8"

[dev-dependencies]
env_logger = "0.6.0"
slog-term = "2"
slog-async = "2"
