[package]
name = "legion"
version = "0.1.0"
authors = ["Thomas Gillen <thomas.gillen@googlemail.com>"]
repository = "https://github.com/TomGillen/legion"
keywords = ["ecs", "game"]
categories = ["game-engines", "data-structures"]
readme = "readme.md"
license = "MIT"
edition = "2018"

[features]
default = ["par-iter", "serde"]
par-iter = ["rayon"]

[dependencies]
slog = { version = "2.4", features = ["nested-values"] }
slog-stdlog = "3"
parking_lot = "0.7"
downcast-rs = "1.0"
itertools = "0.8"
names = "0.11.0"
rayon = { version = "1.0", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
fnv = "1.0"

[dev-dependencies]
env_logger = "0.6.0"
slog-term = "2"
slog-async = "2"
